### ISSUE TITLE
working on fragments?

### ISSUE THREAD

**Issue by CanRau** [ivopetkov/html5-dom-document-php#1]
is it working on html fragments, too? can't get it working
my html `<p>paragraph</p><p>paragraph2</p>`
and my php

    $dom = new \IvoPetkov\HTML5DOMDocument();
    $dom->loadHTML($content);
    $paragraphs = $dom->getElementsByTagName('p');
    var_dump($paragraphs);
the backslash because my php got another namespace..

**Comment by ivopetkov** [comment]
The fragments are automatically inserted into a body element, so they work fine. I tested your code on my machine (PHP 7.1 with libxml v2.9.4), and it works great. Can you please share your environment.

**Comment by CanRau** [comment]
got it working now, don't know what happened yesterday..what is the proper/best way to strip the added doctype and body to get the initial fragment? str_replace or are there any other options?

**Comment by ivopetkov** [comment]
I'd recommend:
```php
$content = $dom->querySelector('body')->innerHTML;
```

**Comment by CanRau** [comment]
Thanks and sorry for not responding..I had to hold this work for now..
