### ISSUE TITLE
Allow for selectors with custom tags / dashes in name

### ISSUE THREAD

**Issue by bkonetzny** [ivopetkov/html5-dom-document-php#10]
The current tagname selectors (`preg_match('/^[a-z0-9]+$/', $selector)`) in `internalQuerySelectorAll` only allow for normal HTML5 tags to match. Thus it is not possible to parse a document containing custom elements (https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements) which are required to to have a dash (`-`) in the name.

It would be great if the default selector regex would include `-` as an allowed character in tagnames OR if the selector regex could be overwritten when initializing the class.

Please tell me which solution you would prefer - if any. I'm happy to provide a PR for this.

**Comment by ivopetkov** [comment]
I think adding `-` support in the regex is the way to go.
Thanks for your contribution.
