### ISSUE TITLE
Elements with the same id value are removed

### ISSUE THREAD

**Issue by ygoe** [ivopetkov/html5-dom-document-php#21]
When I have multiple elements with the same `id` value in the document, then only the first one will remain in the document. This is a problem for me because I write HTML content in multiple languages and filter it to a single language before rendering the page. When an element with an `id` occurs in multiple language parts, the second and more are missing and only the first element is kept.

Why does this happen? The id is supposed to be unique in the browser, and it will be, but it may not be the first instance that makes it to the browser. It may also be the second one when the first instance is removed before sending the final document to the browser.

**Comment by ivopetkov** [comment]
This is an interesting case. Here are some facts:
1. The native DOM library (DOMDocument) triggers a warning for duplicate element IDs that can be disabled in not so elegant way.
2. Duplicate elements IDs is not a valid HTML.
3. HTML5DomDocument (my library) automatically removes them to ensure the document is valid for future manipulations.

Maybe we can add an option to `loadHTML()` (and some other places) to allow duplicate IDs. What do you think?

**Comment by manychois** [comment]
I don't like the idea of silently removing the duplicate id elements, nor ignoring them. 
I would vote for the action to raise an error as soon as it detects such issue.
Maybe we can call this a strict mode?

**Comment by ivopetkov** [comment]
I agree with @manychois. The default behavior should be a thrown error. I'm sorry I didn't do this in first place.

I need your help to decide how to implement it. Here are some of my thoughts:
1. I think an option to ignore duplicate ids will be helpful (just like the browsers ignore them).
2. DOMDocument::loadHTML and HTML5DOMDocument::loadHTML already has support for options. Maybe define a new one called HTML5_DOM_DOCUMENT_IGNORE_DUPLICATE_IDS.
3. HTML5DOMDocument::insertHTML method has similar problem. Maybe add the same option here too.

These look like breaking changes so I think we are headed towards a new major release (v2.0). Do you have any other ideas to take into account?

**Comment by ivopetkov** [comment]
I've done some tests interacting with HTML with duplicate IDs.

The HTML code:
```html
<html>
    <body>
        <div id="example">1</div>
        <div id="example">2</div>
    </body>
</html>
```

In browsers (JavaScript):
`document.getElementById('example')` - returns the first element
`document.querySelector('[id="example"]')` - returns the first element
`document.querySelectorAll('[id="example"]')` - returns both elements

DomDocument (PHP):
`$dom->getElementById('example')` - returns the first element

This behavior looks consistent... and OK, so we should do the same with these methods.

**Comment by ivopetkov** [comment]
Guys, I've pushed some changes (in master branch) that I think will solve the problems above and make the library easier to use:
1. Removed silent duplicate elements removal and optimizations.
2. Added HTML5DOMDocument::ALLOW_DUPLICATE_IDS option to disable the duplicate elements ids exception in loadHTML()
3. Added the [modify()](https://github.com/ivopetkov/html5-dom-document-php/blob/master/docs/markdown/ivopetkov.html5domdocument.modify.method.md) method to allow specific optimizations and fixes.

The docs are updated too to reflect the changes in the master branch.

What do you think? Is the change good enough for v2.0?

**Comment by ivopetkov** [comment]
Happy to share with you that v2.0.0 is just released. The issue with elements with the same ids is handled in a familiar way (the DomDocument way). Now you can pass HTML5DOMDocument::ALLOW_DUPLICATE_IDS to loadHTML() to prevent errors.

**Comment by geri777** [comment]
So how can I modify the ALLOW_DUPLICATE_IDS setting? 
modify() does not list this option - and I have no clue how to use modify() anyway.

**Comment by ivopetkov** [comment]
ALLOW_DUPLICATE_IDS is a loadHTML() option. Here is an example:
```php
$dom = new HTML5DOMDocument();
$dom->loadHTML($html, HTML5DOMDocument::ALLOW_DUPLICATE_IDS);
```
