### ISSUE TITLE
Error when loading fragment

### ISSUE THREAD

**Issue by barrychapman** [ivopetkov/html5-dom-document-php#25]
I am attempting to load a fragment like this:

    public function __construct($html) {
        $this->dom  = new HTML5DOMDocument('1.0', 'UTF-8');
        $this->dom->loadHTML($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
    }

However - i get the following error:

<b>Fatal error</b>:  Uncaught Error: Call to a member function removeChild() on null in /var/www/html/merged.itechintranet/libs/html5dom/HTML5DOMDocument.php:162
 
I did a step through it, and saw that it is indeed erroring there. I tried wrapping my fragment in another node, and also without.

**Comment by ivopetkov** [comment]
Just released v2.0.1 when it's fixed.
