### ISSUE TITLE
error blogspot duplicate tag

### ISSUE THREAD

**Issue by arielesp** [ivopetkov/html5-dom-document-php#29]
trying read url from blogspot
https://xvnudes.blogspot.com/2019/07/negao-socando-de-4-e-marido-corno.html

using latest version, I receive a error

using old version, 0.6, work fine.

**Comment by ivopetkov** [comment]
In v2 there is a option named HTML5DOMDocument::ALLOW_DUPLICATE_IDS that must be provided to HTML5DOMDocument::loadHTML(). I believe this may fix the situation for you.
