### ISSUE TITLE
"Simple Html Dom Parser": replace "\DOMDocument" with "\IvoPetkov\HTML5DOMDocument"

### ISSUE THREAD

**Issue by voku** [ivopetkov/html5-dom-document-php#30]
Hi,

I have some problems by replacing a "\DOMDocument" with "\IvoPetkov\HTML5DOMDocument", maybe you can help me here. :)

Source: https://github.com/voku/simple_html_dom/commit/7fdc9eb2e3dc6c079050707d06097fd5ebe0bd9b

Tests: https://travis-ci.org/voku/simple_html_dom/jobs/582982466

Problems:
1. I use ```$this->document->importNode``` + ```$this->document->appendChild``` (Source: HtmlDomParser::__construct) but this is not working because "$this->document->loaded" is not set to ```true``` in this cases.

e.g.
```php
$str = '<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF8"><title>jusqu’à 51% de rabais!</title></head><body></body></html>';

$html = HtmlDomParser::str_get_html($str);

$title = $html->findOne('title');

static::assertSame('jusqu’à 51% de rabais!', $title->innerHtml);
```

2. I use ```$ownerDocument->importNode``` (Source: SimpleHtmlDom->replaceTextWithString()) to modify the original DomDocument, but I think you prevent this (via clone)? Maybe you can give access to the reference, so that we can change the dom?

e.g.:
```php
$str = <<<'HTML'
<form name="form1" method="post" action=""><input type="checkbox" name="checkbox1" value="checkbox1" checked>中文空白</form>
HTML;

$html = HtmlDomParser::str_get_html($str);

foreach ($html->findMulti('input') as $e) {
    $e->outertext = '[INPUT]';
}

static::assertSame('<form name="form1" method="post" action="">' . "\n" . '[INPUT]中文空白</form>', (string) $html);
``` 

3. "&nbsp;" are lost after I use ```HTML5DOMDocument->saveHTML()```?

**Comment by ivopetkov** [comment]
Hi, I'm sorry for not responding to this issue for so long. Could you provide some HTML5DOMDocument code that I can check out?

**Comment by ivopetkov** [comment]
Closing reason: Inactive thread.
