### ISSUE TITLE
html5-dom-document-internal-entity in $domNode->nodeValue

### ISSUE THREAD

**Issue by MrMadClown** [ivopetkov/html5-dom-document-php#31]
Assuming we have following HTML Snippet:
`<p><span>Lorem Ipsum</span> — <span>dolor sit amet, </span></p>`

If we load the Doument into a HTML5DOMDocument, and get the `p` Tag through the `query`method, `$domNode->nodeValue` would result in
`Lorem Ipsum html5-dom-document-internal-entity1-mdash-end dolor sit amet, `

Is this a Bug? Or am I using it wrong?

**Comment by ivopetkov** [comment]
It looks like a bug, but I cannot reproduce it using the latest HTML5DOMDocument on PHP 7.1. Can you please send me a little demo that demonstrates the problem. Environment information can be useful too.

**Comment by MrMadClown** [comment]
Hey, I wrote a PHPUnit Test for this.
https://gist.github.com/MrMadClown/0799805d63d55c3e7066702f4037b312
I forgot to mention that I query the Node with XPath. That was probably relevant. Sorry for that.

**Comment by ivopetkov** [comment]
I've never tested it with XPath. HTML5DOMDocument takes advantage of DOMDocument's support for registering custom node classes, but as you've found they don't work as expected in this case.

At the moment I would like to recommend:
```php
$dom = new HTML5DOMDocument();
$dom->loadHTML('...');
$elements = $dom->querySelectorAll('p'); // The popular JS syntax
```

**Comment by MrMadClown** [comment]
Okay, I might look into this then, since I am pretty set on XPath.
Looking at this example https://www.php.net/manual/de/domdocument.registernodeclass.php
XPath should actually work.

**Comment by MrMadClown** [comment]
Well it returns your extended Node. You could probably override that value in the constructor? Or implement a getter.

\DOMNode::$textContent probably has the same 'issue'

**Comment by ivopetkov** [comment]
I like the getters solution. Thanks.
