### ISSUE TITLE
query selector "div.classname > a" return empty

### ISSUE THREAD

**Issue by ellenus** [ivopetkov/html5-dom-document-php#33]
Hi,
I try to run `querySelectorAll('div.classname > a')` but always get empty result.
and since I want the direct child, chained query can't solve my problem.

will this kind of selector be supported?
or any way I can workaround?
thank you.

**Comment by mattiaz9** [comment]
I don't think it's supported. I managed to do it by chaining the selectors like that:
`$dom->querySelector('div.classname')->querySelectorAll('a')`

This will throw an error if one of the selector returns null.

**Comment by ivopetkov** [comment]
It's supported, but there was a bug. It's now fixed in v2.2.3.

**Comment by lucastecoff** [comment]
Hey, does not support the :last-child selector, you can verify?

**Comment by ivopetkov** [comment]
Yes, it's currently not supported. I will add it in the next couple of days.

**Comment by ivopetkov** [comment]
It'll take longer than couple of days :(
You can use querySelectorAll() and pick the last one for now.

**Comment by lucastecoff** [comment]
@ivopetkov, ok my friend, I hope. 😄
