### ISSUE TITLE
Unsupported selector in version 2.2.3

### ISSUE THREAD

**Issue by mattiaz9** [ivopetkov/html5-dom-document-php#34]
I get this error after the last release (2.2.3):
_"Unsupported selector (#productDescription)" on line 510 of vendor/ivopetkov/html5-dom-document-php/src/HTML5DOMDocument/Internal/QuerySelectors.php_

Error I don't get after changing the line 229 of QuerySelectors.php to the previous pattern:
`$simpleSelectors['(?:[a-z0-9\-]*)#(?:.+)'] = ...`

This error also appears to occur only with selectors containing uppercase characters.

**Comment by ivopetkov** [comment]
Thanks for pointing this out. Case sensitivity for all selectors was not handled correctly at all. This is now fixed in v2.2.4.
Could you please confirm its working for you too.

**Comment by mattiaz9** [comment]
Yes I can confirm it works now.
