### ISSUE TITLE
IDE says "Undefined type 'IvoPetkov\HTML5DOMDocument'"

### ISSUE THREAD

**Issue by geri777** [ivopetkov/html5-dom-document-php#37]
I am using Intelephense with VSCode. When using the namespace I get an error, saying that the type of the namespace object is not defined. Running the code works fine.  Is there anything I can do? The problem with this is, that code completion does not work.

**Comment by ivopetkov** [comment]
I'm using Intelephense too and it works fine. I have not made any specific configurations, so I believe it should work for you too.

**Comment by geri777** [comment]
I have just found out that it works well if I just include the autoload.php, but it does not work when I use composer.

``
	require('html5-dom-document-php/autoload.php');
	use IvoPetkov\HTML5DOMDocument;

**Comment by geri777** [comment]
Obviously VSCode does not re-index automatically all dependencies after a composer installation. So you have to close / re-open VSCode after each composer installation, or use an index command as described below:

https://github.com/bmewburn/vscode-intelephense/issues/711

**Comment by ivopetkov** [comment]
Thank you, did not know that.
