### ISSUE TITLE
Example not working ('Unsupported selector')

### ISSUE THREAD

**Issue by morosanuae** [ivopetkov/html5-dom-document-php#4]
Hi,
I tried the example with querying the 'h1' tag and it throws me 'Unsuported selector' error. I tried also with other tag types (e.g. 'div') or query (e.g. '.content') and it's working ok.
Is it a bug or there's something else I'm missing?
Thanks.

**Comment by ivopetkov** [comment]
Yep, it was a bug and it's fixed now. A new release (v0.4.5) is available.

**Comment by morosanuae** [comment]
It seems to be working now. Thanks!
