### ISSUE TITLE
insertBefore() method?

### ISSUE THREAD

**Issue by Dan0sz** [ivopetkov/html5-dom-document-php#42]
Hi,

I looked through the documentation, but I couldn't find it, so that's why I'm submitting this issue:

Is it possible to insert an element at the top of the parent element? E.g. 

````
$document = new IvoPetkov\HTML5DOMDocument();
$document->load($html);
$document->insertHTML("<html><head><link rel='stylesheet' href='$url' /></head></html>");
```` 

Using this snippet of code, the stylesheet `$url` is appended to the head (at the bottom of the list). But sometimes it's preferable to load a stylesheet before another stylesheet.

Is there an option to insert the element before the other elements?

**Comment by ivopetkov** [comment]
There is a target argument in `insertHTML()`, but it only supports elements in the body.
I'd recommend moving the new element to its proper place after inserting it.

```php
$html = "<html><head><link rel='stylesheet' href='URL1'/></head></html>";
$dom = new \IvoPetkov\HTML5DOMDocument();
$dom->loadHTML($html);
$dom->insertHTML("<html><head><link rel='stylesheet' href='URL2'/></head></html>");
$head = $dom->querySelector('head');
$head->insertBefore($head->lastChild, $head->firstChild);
echo $dom->saveHTML();

// Output:
// <html><head><link rel="stylesheet" href="URL2"><link rel="stylesheet" href="URL1"></head></html>
```

**Comment by Dan0sz** [comment]
Cool, that might work. Thanks!

**Comment by Dan0sz** [comment]
For the sake of completion, I wanted to share what eventually made it work.

![afbeelding](https://user-images.githubusercontent.com/18595395/120322111-58053380-c2e4-11eb-91d9-bd4b7e654780.png)

Apparently my `$head` was garbled with `DOMText` nodes, so I just loop through all the elements until I find a proper `DOMElement`.

Thanks for the help!
