### ISSUE TITLE
Insert HTML without modifying DOM

### ISSUE THREAD

**Issue by Dan0sz** [ivopetkov/html5-dom-document-php#43]
On pages which contain invalid HTML, this app seems to move the element to a place where it is valid. Effectively breaking styling.

I think it happens upon save() -- some sort of validation mechanism?

Is there a way to avoid this? So it just adds the element, but it leaves the rest of the DOMDocument intact?

**Comment by ivopetkov** [comment]
That's a 'feature' of the native DOMDocument library, and it's expected because it's trying to convert the code into objects.

I'd recommend surrounding the invalid code in <![CDATA[ ... ]]> before constructing the DOMDocument.

**Comment by Dan0sz** [comment]
Could you expand on the surrounding the invalid code part? A simple code example would suffice :-)

**Comment by ivopetkov** [comment]
I've just realized that the `<![CDATA[ ... ]]>` past was not visible in my previous reply. This should work for code in `<script>` and `<style>` tags.

**Comment by Dan0sz** [comment]
Ah, that makes things a lot clearer! ;-) 

Okay, final question: obviously there is a built-in way to detect the invalid HTML elements. Is it possible for me to trigger this feature on a string containing HTML, or a DOMDocument loaded with loadHTML($string)?

**Comment by ivopetkov** [comment]
I don't think DOMDocument provides such API. HTML5DOMDocument does not too.

**Comment by Dan0sz** [comment]
Well, that's a shame. Thnx anyway!
