### ISSUE TITLE
ALLOW_DUPLICATE_IDS

### ISSUE THREAD

**Issue by CebZnfgreCUC** [ivopetkov/html5-dom-document-php#45]
How to fix it while function querySelector returns: "A DOM node with an ID value "RenderButton" already exists! Pass the HTML5DOMDocument::ALLOW_DUPLICATE_IDS option to disable this check." ?

**Comment by ivopetkov** [comment]
Here is an example:
`$document->loadHTML($html, HTML5DOMDocument::ALLOW_DUPLICATE_IDS);`
