### ISSUE TITLE
Edge Side Includes are not supported

### ISSUE THREAD

**Issue by Dan0sz** [ivopetkov/html5-dom-document-php#46]
Hi!

When working with your library on a server running Varnish, Edge Include Tags (`<esi:include ... >`) are rewritten to `<include ... >`, while they should be left alone to be handled by Varnish.

![esi-include-tag-affected](https://user-images.githubusercontent.com/18595395/131642139-48d96b03-651c-41b4-84d2-7db85e1ce0d3.png)

As far as I know the <esi> markup is valid XML/HTML5. This is what I could find in the W3C docs: https://www.w3.org/TR/esi-lang/

Is there any way to add support for this? Or can you provide a workaround?

**Comment by ivopetkov** [comment]
This library (HTML5DOMDocument) uses internally the native DomDocument library (which is very strict), and after looking at the specs I don't think that "esi:include" is a valid tag name.
I'd recommend replacing "<esi:include" with "<esi-include" before calling loadHTML() and then replacing it back after calling saveHTML().

**Comment by Dan0sz** [comment]
Ok, thanks. I'll try that!
