### ISSUE TITLE
Html Entities are not preserved

### ISSUE THREAD

**Issue by florin-botea** [ivopetkov/html5-dom-document-php#54]
`<div data-x=">"></div>`
is resulting 
`<div data-x="&gt;"></div>`
as output in browser view-source, or writen in a test file. 
I am not using any special configurations, only init the library with a html string.
Thanks!

**Comment by ivopetkov** [comment]
My library is based on the native DOMDocument library. It's the one that encodes the special character in your example. I think this is the right thing to do. Here is the reason why: https://www.w3schools.com/html/html_entities.asp

**Comment by florin-botea** [comment]
no longer available
