### ISSUE TITLE
Need help..

### ISSUE THREAD

**Issue by ranrinc** [ivopetkov/html5-dom-document-php#6]
I'm new at php and would like to parse out this..

based on this parse
echo $dom->querySelector('.packt-js-countdown')->outerHTML;

I got
`<span class="packt-js-countdown" data-countdown-to="1504393200"></span>`

However I need to get 1504393200

How should I do my querySelector correctly? Thanks in advance

**Comment by ivopetkov** [comment]
Can you please send me a snippet I can run.

**Comment by ranrinc** [comment]
Hi @ivopetkov I just lost my script (I believe I though I already posted it here) Anyway want to change the way I used to parse HTML so, let me post it here

`<?php

require __DIR__ . '/vendor/autoload.php';

date_default_timezone_set('Asia/Jakarta');

use GuzzleHttp\Client;

$client = new Client();
$uri = 'https://www.packtpub.com/packt/offers/free-learning';
$response = $client->get($uri);
$text = $response->getBody();

$packtPageXpath = returnXPathObject($text);

$TheTime = $packtPageXpath->query('//span[@class="packt-js-countdown"]/@data-countdown-to');
if ($TheTime->length > 0) 
{
	$timestamp = $TheTime->item(0)->nodeValue;
}

$overview = $packtPageXpath->query('//img[@class="bookimage"]/@src');
if ($overview->length > 0) {
	$BookImg = $overview->item(0)->nodeValue;
}

function returnXPathObject($item) 
{
    $xmlPageDom = new DomDocument();
    @$xmlPageDom->loadHTML($item);
    $xmlPageXPath = new DOMXPath($xmlPageDom);
    return $xmlPageXPath;
}`

The outcome is the time which is changes everytime (inside packt-js-countdown) and grab the link of images (inside bookimage). Now for book images sometime didn't work due to sometimes the books name have ' in it. Hoping that using your code I can get it better.

Thanks in advance.

**Comment by ivopetkov** [comment]
I believe you need:
`$dom->querySelector('.packt-js-countdown')->getAttribute('data-countdown-to')`

**Comment by ranrinc** [comment]
@ivopetkov first of all thank you so much for all your help.

I did make everything else accept for this one

It doesn't show anything...
`echo $dom->querySelector('.dotd-main-book-image float-left')->getAttribute('href');`

This is the original script
`$release = $packtPageXpath->query('//div[@class="dotd-main-book-image float-left"]/a/@href');`

**Comment by ivopetkov** [comment]
I've tested it with ...
```
use IvoPetkov\HTML5DOMDocument;

$dom = new HTML5DOMDocument();
$dom->loadHTML('<html><body><a href="http://example.com/" class="dotd-main-book-image float-left">text</a></body></html>');
echo $dom->querySelector('.dotd-main-book-image float-left')->getAttribute('href');
// Outputs: http://example.com/
```
... and it works as expected. Please, check carefully the HTML code you provide in `loadHTML()`.

**Comment by ranrinc** [comment]
Hi @ivopetkov,

This is how the html was written and I can't grab the URL

```
					<div class="dotd-main-book-image float-left">

						<a href="/web-development/android-design-patterns-and-best-practice">```

anyway thanks for all the help and I hope you can help me with this one more.

**Comment by ivopetkov** [comment]
Try with:
`$dom->querySelector('.dotd-main-book-image float-left')->querySelector('a')->getAttribute('href');`
